### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by lsmith77** [sblondon/pluralizefr#3]
Would you be interested in registering the package on https://pypi.org/ ?

**Comment by sblondon** [comment]
I didn't think someone uses it (or wants to use it) currently. If it's the case, I can publish it on PyPI.

**Comment by lsmith77** [comment]
I want to use it, so it would be very helpful if you could publish it. Thx!

**Comment by sblondon** [comment]
@lsmith77 `pluralizefr` is now on [pypi.org](https://pypi.org/project/pluralizefr/).

I will probably push others versions with minor cleanings in few days or weeks.

The package requires python3.8+. Is it a problem for you?

**Comment by lsmith77** [comment]
awesome. I am on python 3.12
